// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Sun Oct 29 17:18:39 2023

BB_SYSTEM BB_SYSTEM_inst(
	.BB_SYSTEM_max7219DIN_Out(BB_SYSTEM_max7219DIN_Out_sig) ,	// output  BB_SYSTEM_max7219DIN_Out_sig
	.BB_SYSTEM_max7219NCS_Out(BB_SYSTEM_max7219NCS_Out_sig) ,	// output  BB_SYSTEM_max7219NCS_Out_sig
	.BB_SYSTEM_max7219CLK_Out(BB_SYSTEM_max7219CLK_Out_sig) ,	// output  BB_SYSTEM_max7219CLK_Out_sig
	.BB_SYSTEM_startButton_Out(BB_SYSTEM_startButton_Out_sig) ,	// output  BB_SYSTEM_startButton_Out_sig
	.BB_SYSTEM_leftButton_Out(BB_SYSTEM_leftButton_Out_sig) ,	// output  BB_SYSTEM_leftButton_Out_sig
	.BB_SYSTEM_rightButton_Out(BB_SYSTEM_rightButton_Out_sig) ,	// output  BB_SYSTEM_rightButton_Out_sig
	.BB_SYSTEM_CLOCK_50(BB_SYSTEM_CLOCK_50_sig) ,	// input  BB_SYSTEM_CLOCK_50_sig
	.BB_SYSTEM_RESET_InHigh(BB_SYSTEM_RESET_InHigh_sig) ,	// input  BB_SYSTEM_RESET_InHigh_sig
	.BB_SYSTEM_startButton_InLow(BB_SYSTEM_startButton_InLow_sig) ,	// input  BB_SYSTEM_startButton_InLow_sig
	.BB_SYSTEM_leftButton_InLow(BB_SYSTEM_leftButton_InLow_sig) ,	// input  BB_SYSTEM_leftButton_InLow_sig
	.BB_SYSTEM_rightButton_InLow(BB_SYSTEM_rightButton_InLow_sig) 	// input  BB_SYSTEM_rightButton_InLow_sig
);

defparam BB_SYSTEM_inst.DATAWIDTH_BUS = 8;
defparam BB_SYSTEM_inst.PRESCALER_DATAWIDTH = 23;
defparam BB_SYSTEM_inst.DISPLAY_DATAWIDTH = 12;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_7 = 'b00010000;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_6 = 'b00111000;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_5 = 'b01111100;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_4 = 'b01111100;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_3 = 'b00111000;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_2 = 'b00010000;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_1 = 'b00000000;
defparam BB_SYSTEM_inst.DATA_FIXED_INITREGPOINT_0 = 'b00010000;
